config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  
  get '/register', to: 'sessions#register'
  post '/register', to: 'sessions#user_create'

  get '/login', to: 'sessions#login', as: 'login'
  post '/login', to: 'sessions#user_login'
  get '/logout', to: 'sessions#destroy'

  get '/locations/results', to: 'locations#results', as: 'results'

  get '/team', to: 'basics/team#index', as: 'team'

  get '/about', to: 'basics/about#index', as: 'about'

  get '/contact', to: 'basics/contact#index', as: 'contact'

  get '/faq', to: 'basics/faq#index', as: 'faq'
  
  resources :users do
    get '/', to: 'users#index', as: 'dashboard'
    resources :tips
    resources :investigations
    resources :locations
  end
end

app/controllers/investigations_controller.rb
class InvestigationsController < ApplicationController
  include AnimalHelper
  include Displayable
  
  before_action :set_user_id

  def index
    @page = 1
    @user_id = params[:user_id]
    @investigations = InvestigationFacade.get_all_investigations(@page)
    process_investigations
  end
  
  def show    
    @investigation = InvestigationFacade.get_investigation(params[:id])
  end

  private
    def process_investigations
      @investigations.compact!
      @investigations.shuffle!
      @investigation_images = @investigations.each_with_index do |investigation, idx|
        if idx % 20 == 0
          random_dog
        elsif idx % 10 == 0
          random_dog
        else
          investigation
        end
      end
    end
end

app/helpers/investigation_helper.rb
module InvestigationHelper
  def image_link_check(url)
    Faraday.new do |conn|
      response = conn.get(url)
      response.status
    end
  end

  def next_page
    @page = params[:page].to_i
  end
end

app/views/investigations/_c_copy.erb
<div id="carouselExampleControls" class="carousel slide">
  <div class="carousel-inner">
    <% until @investigations.empty? %>
      <div class="carousel-item active">
        <%= if @investigations.last.mugshot[:original] != "nil" 
              @investigation = @investigations.pop
            end 
          image_url "#{@investigation.mugshot[:original]}", height: '500', class: 'mx-auto d-block'
        %>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
    <div class="position-center"><%= link_to "See More Details", user_investigation_path(@user, @investigation.uid), class: "btn btn-danger rounded" %></div>

app/views/investigations/_carousel.html.erb
<% investigations = InvestigationsCarousel.new %>

<%= carousel_for(investigations.image_urls(@investigations)) %>

app/views/investigations/_images.html.erb
  <% if @investigation.files.is_a?(InvestigationPoro) %>
    <div class="pdf">
      <iframe src="http://docs.google.com/gview?url=<%= @investigation.files %>&embedded=true" style="width:100px;" frameborder="0">
      </iframe>
    </div>
  <% else %>
    <% @investigation.images.each do |img| %>
      <% if image_link_check(img[:original]) == 200 %>
        <figure>
          <%= image_tag(img[:original], class: 'mx-auto d-block', width: '150') %>
          <figcaption><%= img[:caption] %></figcaption>
        </figure>
      <% else %>
        <figure>
          <%= image_tag(random_cat, class: 'mx-auto d-block', width: '150') %>
          <figcaption><%= img[:caption] %></figcaption>
        </figure>
      <% end %>
    <% end %>
  <% end %>

app/views/investigations/_inv_tabs.html.erb
<div class="card">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link active" aria-current="true" href="#descr" data-bs-toggle="tab">Description</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#traits" data-bs-toggle="tab">Traits</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#alerts" data-bs-toggle="tab">Alerts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#rewards" data-bs-toggle="tab">Reward</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#subjects" data-bs-toggle="tab">Subjects</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <div class="tab-content">
      <div class="tab-pane" id="descr">
        <p class="card-text me-auto"><%= @investigation.description %><%= @investigation.status %></p>
      </div>
    </div>
    <div class="tab-content">
      <div class="tab-pane" id="traits">
        <table class="card-text me-auto">
          <tr class="row"><thead>
            <th class="col-2"> Alias(es) </th>
            <th class="col-2"> Dates of Birth Used </th>
            <th class="col-1"> Sex </th>
            <th class="col-1"> Race </th>
            <th class="col-1"> Hair Color </th>
            <th class="col-1"> Eyes </th>
            <th class="col-1"> Weight </th>
            <th class="col-2"> Scars and Marks </th>
          </thead></tr>
          <tr class="row"><tbody>
            <th class="col-2">
              <%= @investigation.aliases %>
            </th>
            <th class="col-2">
              <%= @investigation.dates_of_birth_used[0] %>
            </th>
            <th class="col-1">
              <%= @investigation.sex %>
            </th>
            <th class="col-1">
              <%= @investigation.race.capitalize %>
            </th>
            <th class="col-1">
              <%= @investigation.hair %>
            </th>
            <th class="col-1">
              <%= @investigation.eyes %>
            </th>
            <th class="col-1">
              <%= @investigation.weight %> 
            </th>
            <th class="col-2">
              <%= @investigation.scars_and_marks %>
            </th>
          </tbody></tr>
        </table>
      </div>
    </div>
    <div class="tab-content">
      <div class="tab-pane fade" id="alerts">
        <table class="card-text me-auto">
          <tr class="row"><thead>
            <th class="col-1">Warning</th>
            <th class="col-1">Caution</th>
          </thead></tr>
          <tr class="row"><tbody>
            <th class="col-1">
              <%= @investigation.warning_message %>
            </th>
            <th class="col-1">
              <%= @investigation.caution %>
            </th>
          </tbody></tr>
        </table>
      </div>
    </div>
    <div class="tab-content">
      <div class="tab-pane fade" id="reward">
        <div class="card-text me-auto">
          <h5>Reward</h5>
          <p>$<%= @investigation.reward %></p>
        </div>
      </div>
    </div>
    <div class="tab-content">
      <div class="tab-pane fade" id="subjects">
        <div class="card-text me-auto">
          <ul>
            <% @investigation.subjects.map do |sub| %>
              <li><%= sub %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/investigations/index.html.erb
<%= render partial: 'investigations/carousel', cache: true %>

<%= content_for :nav_links do %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Map", user_locations_path(@user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Browse Investigations", user_investigations_path(@user), class: "nav-link" %>
      </li>
    </ul>

    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <a class ="nav-link" href=<%= logout_path %>>Logout
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
          </svg>
        </a>
      </li>
    </ul>
  </div>
<% end %>

app/views/investigations/replace.turbo_stream.erb
<%= turbo_stream.replace "investigations" do %>
  <template>
    <div id="results">
      <span>
        <h2><%= @city %></h2>
        <turbo-stream action="remove" target="investigations">
          <a href="/locations">clear</a>
        </turbo-stream>
      </span>

      <br>

      <h3>Results</h3>
      <table id="<%= @city %>-table">
        <thead>
          <tr class="row">
            <th class="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @investigations.each do |inv| %>
            <tr class="row">
              <td class="col"><%= link_to inv.title.titleize + " - " + inv.description.truncate(50), investigation_path(inv) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </template>
<%# </turbo-stream> %>
<% end %>

app/views/investigations/show.html.erb
<div class="row">
  <div class="mx-auto">
    <div class="card border-0 shadow rounded-3">
      <div class="card-body">
        <%= render 'images' %>

        <h1>WANTED:</h1> 
        <p><%= @investigation.title %></p>

        <%= render 'inv_tabs' %>

        <br>

        <%= link_to "Submit a Tip", new_user_tip_path(@user), class: "btn btn-outline-danger", params: { uid: "#{@investigation.uid}", name: "#{@investigation.title}" } %>
      </div>
    </div>
  </div>
</div>

<%= content_for :nav_links do %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Map", user_locations_path(@user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Browse Investigations", user_investigations_path(@user), class: "nav-link" %>
      </li>
    </ul>

    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <a class ="nav-link" href=<%= logout_path %>>Logout
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
          </svg>
        </a>
      </li>
    </ul>
  </div>
<% end %>