config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  
  get '/register', to: 'sessions#register'
  post '/register', to: 'sessions#user_create'

  get '/login', to: 'sessions#login', as: 'login'
  post '/login', to: 'sessions#user_login'
  get '/logout', to: 'sessions#destroy'

  get '/locations/results', to: 'locations#results', as: 'results'

  get '/team', to: 'basics/team#index', as: 'team'

  get '/about', to: 'basics/about#index', as: 'about'

  get '/contact', to: 'basics/contact#index', as: 'contact'

  get '/faq', to: 'basics/faq#index', as: 'faq'
  
  resources :users do
    get '/', to: 'users#index', as: 'dashboard'
    resources :tips
    resources :investigations
    resources :locations
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user_id

  def index
    @tips = TipFacade.users_tips(@user)
  end
  
  def show
    @user = UserFacade.get_user(params[:id])
  end

  def new; end

  private
    def user_params
      params.permit(:first_name, :email, :password, :password_confirmation, :authenticity_token, :commit)
    end
end

app/helpers/user_helper.rb
module UserHelper
  def user_avatar(user, options = {})
    if user.avatar?
      image_tag(user.avatar.url, options)
    else
      image_tag("default_avatar.png", options)
    end
  end

  def user_exists?
    UserFacade.find_user(params[:email])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user, options = {})
    if user.avatar?
      image_tag(user.avatar.url, options)
    else
      image_tag("default_avatar.png", options)
    end
  end

  def user_exists?
    UserFacade.find_user(params[:email])
  end
end

app/views/users/index.html.erb
<h3>My Tips</h5>
  <div class="container $gray-200">
    <div class="list">
      <% @tips.each do |tip| %>
          <div class="list-item">
            <div class="card  border-light mb-3"">
              <h5 class="card-header"><%= link_to "#{find_investigation(tip.uid).title}", user_investigation_path(@user, tip.uid) %></h5>
              <div class="card-body">
                <p class="card-text"><%= tip.description %></p>
                <p class="card-text"><small class="text-muted">Last updated <%= time_ago_in_words(tip.updated_at) %> ago</small></p>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>

<%= content_for :nav_links do %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Map", user_locations_path(@user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Browse Investigations", user_investigations_path(@user), class: "nav-link" %>
      </li>
    </ul>

    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <a class ="nav-link" href=<%= logout_path %>>Logout
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
          </svg>
        </a>
      </li>
    </ul>
  </div>
<% end %>

app/views/users/register.html.erb
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card border-0 shadow rounded-3 my-1">
        <div class="card-body p-4 p-sm-5">
          <h5 class="card-title text-center mb-5 fw-light fs-5">Login</h5>
            <%= form_with url: register_url, local: true do |form| %>
              <div class="form-floating mb-3">
                <%= form.label :email, { for: "floatingInput" } %>
                <%= form.text_field :email, { class: "form-control", id: "floatingInput", placeholder: "name@example.com", required: true } %>
              </div>
              <div class="form-floating mb-3">
                <%= form.label :password, { for: "floatingPassword" } %>
                <%= form.text_field :password, { class: "form-control", id: "floatingPassword", placeholder: "Password", type: "password", required: true } %>
              </div>
              <div class="form-floating mb-3">
                <%= form.label :password_confirmation, { for: "floatingPasswordConfirmation" } %>
                <%= form.text_field :password_confirmation, { class: "form-control", id: "floatingPasswordConfirmation", placeholder: "Password", type: "password", required: true } %>
              </div>

              <div class="d-grid">
                <%= form.submit "Sign Up", type: :submit, class: "btn btn-primary btn-login text-uppercase fw-bold" %>
              </div>
              <hr class="my-3">
              <div class="d-grid">
                <a class="oauth-container btn btn-login white black-text me-3 shadow-sm rounded" href="/auth/google_oauth2" id="oauth-container">
                <img alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" width="16" height="16" target="_blank" />
                  Sign Up with Google
                </a>
              </div>
              <hr>
              <div class="mb-2">
                <%= link_to "Click Here to Login Instead", login_path %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/users/signup.html.erb
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card border-0 shadow rounded-3 my-1">
        <div class="card-body p-4 p-sm-5">
          <h5 class="card-title text-center mb-5 fw-light fs-5">Login</h5>
            <%= form_with url: signup_url, local: true do |form| %>
              <div class="form-floating mb-3">
                <%= form.label :email, { for: "floatingInput" } %>
                <%= form.text_field :email, { class: "form-control", id: "floatingInput", placeholder: "name@example.com", required: true } %>
              </div>
              <div class="form-floating mb-3">
                <%= form.label :password, { for: "floatingPassword" } %>
                <%= form.text_field :password, { class: "form-control", id: "floatingPassword", placeholder: "Password", type: "password", required: true } %>
              </div>
              <div class="form-floating mb-3">
                <%= form.label :password_confirmation, { for: "floatingPasswordConfirmation" } %>
                <%= form.text_field :password_confirmation, { class: "form-control", id: "floatingPasswordConfirmation", placeholder: "Password", type: "password", required: true } %>
              </div>

              <div class="d-grid">
                <%= form.submit "Sign Up", type: :submit, class: "btn btn-primary btn-login text-uppercase fw-bold" %>
              </div>
              <hr class="my-3">
              <div class="d-grid">
                <a class="oauth-container btn btn-login white black-text me-3 shadow-sm rounded" href="/auth/google_oauth2" id="oauth-container">
                <img alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" width="16" height="16" target="_blank" />
                  Sign Up with Google
                </a>
              </div>
              <hr>
              <div class="mb-2">
                <%= link_to "Click Here to Login Instead", login_path %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>