config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  
  get '/register', to: 'sessions#register'
  post '/register', to: 'sessions#user_create'

  get '/login', to: 'sessions#login', as: 'login'
  post '/login', to: 'sessions#user_login'
  get '/logout', to: 'sessions#destroy'

  get '/locations/results', to: 'locations#results', as: 'results'

  get '/team', to: 'basics/team#index', as: 'team'

  get '/about', to: 'basics/about#index', as: 'about'

  get '/contact', to: 'basics/contact#index', as: 'contact'

  get '/faq', to: 'basics/faq#index', as: 'faq'
  
  resources :users do
    get '/', to: 'users#index', as: 'dashboard'
    resources :tips
    resources :investigations
    resources :locations
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_user_id
  
  def show
    @tip = TipFacade.get_tip(@user, params[:id])
    @investigation = InvestigationFacade.get_investigation(@tip.uid)
  end

  def new
    require 'pry'; binding.pry 
    @investigation = InvestigationFacade.get_investigation(params[:uid])
    @investigation = InvestigationFacade.cities_investigations("Denver").first

    @tip = TipFacade.new
  end

  def create
    @tip = @tip.create_tip(tip_params)
    if @tip
      redirect_to :back
      render :notice, "Your tip was submitted successfully."
    else
      redirect_to :new
      render :alert, "We could not submit your tip at this time. Please check your inputs and try again."
    end
  end

  private
    def tip_params
      params.permit(:uid, :location, :date, :time, :description, :user_id)
    end
  
    def find_tip
      @tip = Tip.find_tips(request.env['omniauth.auth'])
    end
end

app/helpers/tip_helper.rb
module TipHelper
  def find_investigation(uid)
    inv = InvestigationFacade.find_investigation(uid)
    InvestigationPoro.new(inv)
  end
end

app/views/tips/new.html.erb
  <%# <div class="dialog dialog-centered">

      <div class="content">
        <div class="header">
          <h5 class="title" id="staticBackdropLabel">Submit a Tip</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div> %>
        <div class="body">
          <%= form_with url: new_user_tip_url, local: true do |f| %>
            <div class="form-group">
              <%= f.label :first_name %>
              <%= f.text_field :first_name, class: "form-control", value: "#{ @investigation.title.split(' ').first }", disabled: true, readonly: true %>
            </div>
            <div class="form-group">
              <%= f.label :last_name %>
              <%= f.text_field :last_name, class: "form-control", value: "#{ @investigation.title.split(' ').last }",  disabled: true, readonly: true %>
            </div>
            <div class="form-group">
              <%= f.label :city %>
              <%= f.text_field :city, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :state %>
              <%= f.text_field :state, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :zip_code %>
              <%= f.text_field :zip_code, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :phone %>
              <%= f.phone_field :phone, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :date %>
              <%= f.date_field :date, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :firsthand %>
              <%= f.check_box :firsthand %>
            </div>
            <div class="form-group">
              <%= f.label :details %>
              <%= f.text_area :details, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :uid, hidden: true %>
              <%= f.text_field :uid, class: "form-control", value: "#{ @investigation.uid }", hidden: true %>
            </div>
            <div class="form-group">
              <%= f.submit "Submit", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
        <div class="cancel-button">
          <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
        </div>
      <%# </div>
<%= content_for :nav_links do %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Map", user_locations_path(@user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Browse Investigations", user_investigations_path(@user), class: "nav-link" %>
      </li>
    </ul>

    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <a class ="nav-link" href=<%= logout_path %>>Logout
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
          </svg>
        </a>
      </li>
    </ul>
  </div>
<% end %>
  </div>
</div> %>

app/views/tips/show.html.erb
<h1>Tip: <%= @tip.uid %></h1>
<h3>Investigation: <%= @investigation.title %>

<p><%= @tip.description %></p>
<p>Location: <%= @tip.location %></p>
<p>Date of occurence: <%= @tip.date %></p>
<p>Submitted on: <%= @tip.created_at.strftime(%A %m %d) %></p>